linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 10
    max-complexity: 12
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/reportportal/goRP/v5
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
    - wsl
    - goerr113
    - godot
    - funlen
    - testpackage
    - nlreturn
    - stylecheck
    - exhaustivestruct
    - exhaustruct
    - varnamelen
    - tagliatelle
    - wrapcheck
    - gomnd
    - gci
    - revive

#run:
#  skip-dirs:
#    - test/testdata_etc

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec

