# .goreleaser.yml
# Build customization
builds:
  - binary: gorp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
