# .goreleaser.yml
env_files:
  github_token: ~/.config/goreleaser/github_token
builds:
  - binary: gorp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
