# .goreleaser.yml
builds:
  - binary: gorp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
env_files:
  # use only one or release will fail!
  github_token: ~/.goreleaser/github