sudo: false
language: go
go:
  - "1.15.x"

env:
  - GO111MODULE=on

before_script:
  - make init-deps

script:
  - make checkstyle build

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/avarabyeu/goRP"
