sudo: false
language: go
go:
  - "1.10"

before_script:
  - make init-deps vendor

script:
  - make build

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/avarabyeu/goRP"
