name: Build

on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    branches:
      - master
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.8' # The Go version to download (if necessary) and use.
#      - name: Install dependencies
#        run: |
#          go version
#          go get -u golang.org/x/lint/golint
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.57.2
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
      # Run build of the application
      - name: Run build
        run: make build

      # Run testing on the code
      - name: Run testing
        run: make test
